name: Ingesta y Limpieza Automática de Datos

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    # Se ejecuta automáticamente todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Script de Ingesta y Limpieza
      run: |
        python main.py

    - name: Hacer Commit y Push de los Cambios Generados
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add src/
        git commit -m "Auto-update: actualización de SQLite, Excel y Reporte de Auditoría" || echo "No hay cambios para subir"
        git push

    - name: Subir Artefactos (Excel y Reporte de Auditoría)
      uses: actions/upload-artifact@v4
      with:
        name: evidencias-ingesta
        path: |
          src/xlsx/cleaned_data.xlsx
          src/static/auditoria/cleaning_report.txt
          src/db/ingestion.db